### ISSUE TITLE
train.txt and val.txt doesn't list all files

### ISSUE THREAD

**Issue by karlHolmquist** [NVlabs/FLAT#5]
Hi,
I'm interested in using the FLAT dataset but I have some questions regarding the scenes used for training and testing.
I started by downloading the kinect data:
`python init.py -c kinect`
Which seems to download ~2000 measurements w/ ground truth depth.

However, when I check the train.txt file, only one example is listed there "1499392477178439" but the folder with results contains ~1100 images.
Similar is true for val.txt(1 listed, ~50 results).
Test.txt however contains all 120 measurements and results.

Is this an unintentional error in the files on the google drive and is it possible to update it with the full list of files used in training/validation?

All the best

**Comment by guoqi1123** [comment]
I am sorry for the late response. The train.txt file only contains an example of how you should list the images for training. You can manually add the name of images to the .txt. In your training script, it can read this txt file to know which images are used for training/validation/testing, so that you do not have to manually divide the data.

**Comment by karlHolmquist** [comment]
Thanks for the response, 
Would it be possible for you to provide the exact settings that were used in the paper for training and testing? Or are the generated measurements provided different from the ones used in the paper?
